<?php

namespace Database\Seeders;

use App\Models\Flight;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FlightSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $flights = [
            [
                'airline' => 'American Airlines',
                'flight_number' => 'AA1234',
                'from_airport' => 'JFK',
                'logo' => null,
                'from_city' => 'New York',
                'to_airport' => 'LAX',
                'to_city' => 'Los Angeles',
                'departure_time' => '2024-12-15T08:30:00Z',
                'arrival_time' => '2024-12-15T11:45:00Z',
                'duration' => '3h 15m',
                'stops' => 'Non-stop',
                'price' => 299.00,
                'class' => 'Economy',
            ],
            [
                'airline' => 'Southwest Airlines',
                'flight_number' => 'WN3456',
                'from_airport' => 'LGA',
                'logo' => null,
                'from_city' => 'New York',
                'to_airport' => 'MIA',
                'to_city' => 'Miami',
                'departure_time' => '2024-12-15T10:30:00Z',
                'arrival_time' => '2024-12-15T13:45:00Z',
                'duration' => '2h 15m',
                'stops' => 'Non-stop',
                'price' => 189.00,
                'class' => 'Economy',
            ],
            [
                'airline' => 'VietJet Air',
                'flight_number' => 'VJ356',
                'from_airport' => 'SGN',
                'logo' => null,
                'from_city' => 'Ho Chi Minh',
                'to_airport' => 'HAN',
                'to_city' => 'Hanoi',
                'departure_time' => '2024-12-20T07:15:00Z',
                'arrival_time' => '2024-12-20T09:20:00Z',
                'duration' => '2h 05m',
                'stops' => 'Non-stop',
                'price' => 95.00,
                'class' => 'Economy',
            ],
            [
                'airline' => 'Vietnam Airlines',
                'flight_number' => 'VN180',
                'from_airport' => 'HAN',
                'logo' => null,
                'from_city' => 'Hanoi',
                'to_airport' => 'DAD',
                'to_city' => 'Da Nang',
                'departure_time' => '2024-12-21T13:30:00Z',
                'arrival_time' => '2024-12-21T14:45:00Z',
                'duration' => '1h 15m',
                'stops' => 'Non-stop',
                'price' => 75.00,
                'class' => 'Economy',
            ],
            [
                'airline' => 'Bamboo Airways',
                'flight_number' => 'QH201',
                'from_airport' => 'SGN',
                'logo' => null,
                'from_city' => 'Ho Chi Minh',
                'to_airport' => 'PQC',
                'to_city' => 'Phu Quoc',
                'departure_time' => '2024-12-22T09:00:00Z',
                'arrival_time' => '2024-12-22T10:00:00Z',
                'duration' => '1h 00m',
                'stops' => 'Non-stop',
                'price' => 65.00,
                'class' => 'Economy',
            ],
            [
                'airline' => 'Qatar Airways',
                'flight_number' => 'QR977',
                'from_airport' => 'HAN',
                'logo' => null,
                'from_city' => 'Hanoi',
                'to_airport' => 'DOH',
                'to_city' => 'Doha',
                'departure_time' => '2024-12-24T01:10:00Z',
                'arrival_time' => '2024-12-24T05:30:00Z',
                'duration' => '8h 20m',
                'stops' => 'Non-stop',
                'price' => 620.00,
                'class' => 'Economy',
            ],
            [
                'airline' => 'Singapore Airlines',
                'flight_number' => 'SQ177',
                'from_airport' => 'SGN',
                'logo' => null,
                'from_city' => 'Ho Chi Minh',
                'to_airport' => 'SIN',
                'to_city' => 'Singapore',
                'departure_time' => '2024-12-23T11:20:00Z',
                'arrival_time' => '2024-12-23T14:20:00Z',
                'duration' => '3h 00m',
                'stops' => 'Non-stop',
                'price' => 180.00,
                'class' => 'Economy',
            ],
            [
                'airline' => 'Emirates',
                'flight_number' => 'EK395',
                'from_airport' => 'SGN',
                'logo' => null,
                'from_city' => 'Ho Chi Minh',
                'to_airport' => 'DXB',
                'to_city' => 'Dubai',
                'departure_time' => '2024-12-25T18:55:00Z',
                'arrival_time' => '2024-12-25T23:55:00Z',
                'duration' => '8h 00m',
                'stops' => 'Non-stop',
                'price' => 540.00,
                'class' => 'Economy',
            ],
            [
                'airline' => 'Cathay Pacific',
                'flight_number' => 'CX766',
                'from_airport' => 'SGN',
                'logo' => null,
                'from_city' => 'Ho Chi Minh',
                'to_airport' => 'HKG',
                'to_city' => 'Hong Kong',
                'departure_time' => '2024-12-19T06:45:00Z',
                'arrival_time' => '2024-12-19T09:55:00Z',
                'duration' => '3h 10m',
                'stops' => 'Non-stop',
                'price' => 210.00,
                'class' => 'Economy',
            ],
            [
                'airline' => 'Thai Airways',
                'flight_number' => 'TG561',
                'from_airport' => 'HAN',
                'logo' => null,
                'from_city' => 'Hanoi',
                'to_airport' => 'BKK',
                'to_city' => 'Bangkok',
                'departure_time' => '2024-12-18T15:10:00Z',
                'arrival_time' => '2024-12-18T17:20:00Z',
                'duration' => '2h 10m',
                'stops' => 'Non-stop',
                'price' => 145.00,
                'class' => 'Economy',
            ],
        ];

        Flight::upsert($flights, ['flight_number'], [
            'airline',
            'from_airport',
            'logo',
            'from_city',
            'to_airport',
            'to_city',
            'departure_time',
            'arrival_time',
            'duration',
            'stops',
            'price',
            'class',
            'updated_at',
        ]);
    }
}
